### ISSUE TITLE
Filter cases by object type, content etc.

### ISSUE THREAD

**Issue by elifila** [equinor/fmu-sumo#324]
In DynaGeo we want to present specific data types to the user, i.e., allow the user to select the data type before selecting the case.  It would be very useful if 'SumoExplorer' could filter on cases containing requested data types.
 
One example is 4D seismic data, which would mean being able to filter out cases containing surfaces where metadata.content == "seismic" and "base" and "monitor" in metadata.date (?).

**Comment by perolavsvendsen** [comment]
This is likely relevant also for others. Not providing this through REST and/or through `fmu-sumo` will be incentive to write own queries directly against Elasticsearch, which is a pattern we don't want. 

Will prioritize this 🚀 

Generalized user story:
As a data consumer, I would like to filter cases on their content, so that I can limit available cases exposed to my users to those that have the necessary data and/or are compliant with the function my user is using.

1. General support for case filtering
2. Specific support for individual use cases, taking the data model into account. Will possibly spark discussions with `fmu-dataio`.

**Comment by equinor-ruaj** [comment]
Added filter to find cases with `4d-seismic`.
Filters for other types can either be added manually or requested to be added as part of the Explorer package.
Docs: https://fmu-sumo.readthedocs.io/en/latest/explorer.html#finding-cases-with-specific-data-types
